// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHzLrsa9qRKaS6iyY6MCYVZXgIAHTnZcE',
    appId: '1:114335724788:web:89318fa19f8848d7419aa1',
    messagingSenderId: '114335724788',
    projectId: 'chatapp-a9ffd',
    authDomain: 'chatapp-a9ffd.firebaseapp.com',
    storageBucket: 'chatapp-a9ffd.appspot.com',
    measurementId: 'G-8XQV8136KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrXRTeX05NLtNhR2LafhthP367LrDhRnA',
    appId: '1:114335724788:android:affb946440d78199419aa1',
    messagingSenderId: '114335724788',
    projectId: 'chatapp-a9ffd',
    storageBucket: 'chatapp-a9ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW-q37h-XjqrYtfRcsgO3tetJOONWjCYU',
    appId: '1:114335724788:ios:95a06d496fe281a1419aa1',
    messagingSenderId: '114335724788',
    projectId: 'chatapp-a9ffd',
    storageBucket: 'chatapp-a9ffd.appspot.com',
    iosClientId:
        '114335724788-mc98eaj80bked0oeec2213rndnbll0dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW-q37h-XjqrYtfRcsgO3tetJOONWjCYU',
    appId: '1:114335724788:ios:95a06d496fe281a1419aa1',
    messagingSenderId: '114335724788',
    projectId: 'chatapp-a9ffd',
    storageBucket: 'chatapp-a9ffd.appspot.com',
    iosClientId:
        '114335724788-mc98eaj80bked0oeec2213rndnbll0dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
